development:
  bucket_name: your_bucket_name
  access_key_id: your_access_key_id
  secret_access_key: your_secret_access_key 

test:
  bucket_name: 
  access_key_id: 
  secret_access_key:

production:
  bucket_name: 
  access_key_id: 
  secret_access_key: